### ISSUE TITLE
Difference between this and philpem repository?

### ISSUE THREAD

**Issue by TRSx80** [trialinfo/ptouch-driver#2]
It seems maybe active development going on here?

**Comment by andreas-gruenbacher** [comment]
This repository is based on the last release (v1.3) before Phil took over maintenance. I've added all of the fixes from Phil's repository that seemed reasonable, replaced some with improved versions, and left out some changes that didn't make sense. On top of that, I've made the driver a bit more maintainable before adding support for a few more recent printers.

**Comment by TRSx80** [comment]
That sounds great!

And thanks for the very fast response!
